/**
 * Gandalf Control-Panel Agent  [Guild integration]
 *
 * The operator-facing agent that drives the Gandalf self-learning loop from Guild.
 * Guild is the cockpit; Gandalf (a Python service on Azure) is the engine. This agent
 * never runs Gandalf's code — it calls Gandalf's REST API through the Guild integration
 * proxy (tools imported below), which Guild builds from guild/openapi.yaml.
 *
 * Agent shape per @guildai/agents-sdk docs (llmAgent): systemPrompt + tools. Input/output
 * are fixed text types; the LLM decides which tools to call from the prompt.
 *
 * SETUP: imports the `gandalf` integration under the `cu2` org (org slug confirmed created).
 * The integration must be created + OpenAPI-imported BEFORE this agent is saved, or the
 * import below won't resolve (see guild/README.md for the exact order).
 */
import { guildTools, llmAgent } from "@guildai/agents-sdk";
// Tools generated by the `gandalf` integration (startRun, getRunStatus, getSummary,
// getResults, listCharts, healthCheck) — operationIds from openapi.yaml.
import { gandalfTools } from "@guildai-services/cu2~gandalf";

const systemPrompt = `
You are the control panel for the Gandalf Protocol — a self-learning multi-agent loop.
Your job is to start learning runs, watch them to completion, and report plainly whether
the run learned. You operate Gandalf entirely through its tools; never invent numbers.

When asked to start a run (default: condition "swarm", rounds 3):
1. Call startRun with the requested condition and rounds. If it returns status "busy"
   (409), tell the operator a run is already in progress and stop — do not start another.
2. Poll getRunStatus. Keep polling while "running" is true. Report progress succinctly
   (phase + training_episodes) as it climbs. If "error" is non-null, stop and report it.
3. When "running" is false, call getSummary. Report:
   - training vs validation episode counts,
   - the score_history means by occasion,
   - a one-line verdict: did training produce a real signal, and is score_history non-empty
     (empty score_history = no training episodes landed = the run did not learn — flag it).
4. Call listCharts and give the operator the chart URLs (the learning-curve visuals live in
   Gandalf's own dashboard; you link to them, you do not draw them).

Be concise and factual. Report exactly what the tools return. If a tool call fails, say so
and what you were trying to do — do not paper over it.
`;

export default llmAgent({
  description: "Starts, monitors, and reports Gandalf self-learning runs.",
  systemPrompt,
  tools: { ...gandalfTools, ...guildTools },
  mode: "multi-turn",
});
